use serde::{Deserialize, Serialize};
use specta::Type;

use crate::value::{ColumnMeta, Row};

/// SQL statement plus execution hints. Drivers may layer their own dialect
/// rewriting, but the host always hands them a query in this shape.
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct Query {
    pub sql: String,
    /// If `Some`, the driver should append (or enforce) a row cap. SPEC §5.4
    /// asks for streamed page-style results — for the first vertical slice we
    /// just return up to `max_rows` rows in one shot.
    pub max_rows: Option<u32>,
    /// Target database. For engines like Postgres where a connection is bound
    /// to one database, the driver routes the query to a pool for this
    /// database (the sidebar can browse several databases per connection).
    /// `None` means "use the connection's default database".
    pub database: Option<String>,
}

impl Query {
    pub fn new(sql: impl Into<String>) -> Self {
        Self {
            sql: sql.into(),
            max_rows: None,
            database: None,
        }
    }

    pub fn with_max_rows(mut self, max_rows: u32) -> Self {
        self.max_rows = Some(max_rows);
        self
    }

    pub fn with_database(mut self, database: impl Into<String>) -> Self {
        self.database = Some(database.into());
        self
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct QueryResult {
    pub columns: Vec<ColumnMeta>,
    pub rows: Vec<Row>,
    /// Database-emitted notices captured while executing this query. Host-side
    /// warnings, validation messages, and truncation badges belong in the
    /// Messages panel, not here.
    pub notices: Vec<DatabaseNotice>,
    /// Whether the current driver path can observe server notice frames.
    pub notice_capture: NoticeCapture,
    /// Server-reported affected-row count for DML, or `None` for SELECT-like
    /// statements where it isn't meaningful.
    pub rows_affected: Option<u64>,
    /// Total elapsed time for the round-trip, measured in the host.
    pub duration_ms: u64,
    /// `true` when the driver truncated the result because it hit
    /// [`Query::max_rows`]. The grid uses this to show a "+ more" badge.
    pub truncated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum NoticeSeverity {
    Panic,
    Fatal,
    Error,
    Warning,
    Notice,
    Info,
    Log,
    Debug,
    Unknown,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq, Eq)]
pub struct DatabaseNotice {
    pub severity: NoticeSeverity,
    /// Engine-native code when available. For Postgres this is the SQLSTATE.
    pub code: Option<String>,
    pub message: String,
    pub detail: Option<String>,
    pub hint: Option<String>,
    /// RFC 3339 timestamp generated by the host when it observes the notice.
    pub timestamp: String,
    pub connection_id: Option<String>,
    pub database: Option<String>,
    pub query_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq, Eq)]
pub struct NoticeCapture {
    pub supported: bool,
    pub reason: Option<String>,
}

impl NoticeCapture {
    pub fn supported() -> Self {
        Self {
            supported: true,
            reason: None,
        }
    }

    pub fn unsupported(reason: impl Into<String>) -> Self {
        Self {
            supported: false,
            reason: Some(reason.into()),
        }
    }
}

/// Whether an execution plan should only estimate the plan or run the
/// statement to collect actual timings. `Analyze` is intentionally explicit:
/// Postgres `EXPLAIN ANALYZE` executes the supplied SQL.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum PlanMode {
    Estimate,
    Analyze,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq)]
pub struct QueryPlan {
    pub mode: PlanMode,
    pub engine: String,
    pub database: Option<String>,
    pub sql: String,
    pub root: PlanNode,
    pub planning_time_ms: Option<f64>,
    pub execution_time_ms: Option<f64>,
    pub duration_ms: u64,
    /// Original engine plan payload for advanced inspection and future richer
    /// renderers. The typed tree above is the stable UI contract.
    pub raw_json: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq)]
pub struct PlanNode {
    pub node_type: String,
    pub relation_name: Option<String>,
    pub schema_name: Option<String>,
    pub alias: Option<String>,
    pub index_name: Option<String>,
    pub join_type: Option<String>,
    pub startup_cost: Option<f64>,
    pub total_cost: Option<f64>,
    pub plan_rows: Option<u64>,
    pub plan_width: Option<u64>,
    pub actual_startup_time_ms: Option<f64>,
    pub actual_total_time_ms: Option<f64>,
    pub actual_rows: Option<f64>,
    pub actual_loops: Option<u64>,
    pub details: Vec<PlanDetail>,
    pub children: Vec<PlanNode>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq, Eq)]
pub struct PlanDetail {
    pub label: String,
    pub value: String,
}

/// Typed request for browsing one table through the grid. This deliberately
/// does not carry executable SQL; each driver owns safe dialect-specific
/// rendering and value binding.
#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq, Eq)]
pub struct TableBrowseRequest {
    pub connection_id: String,
    pub database: Option<String>,
    pub schema: String,
    pub table: String,
    pub limit: Option<u32>,
    pub sorts: Vec<TableSortClause>,
    pub filters: Vec<TableFilterClause>,
    /// When no explicit sort is requested, order by the table primary key if
    /// metadata is available. This keeps table tabs stable without the UI
    /// building an `ORDER BY` string.
    pub primary_key_fallback_ordering: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq, Eq)]
pub struct TableSortClause {
    pub column: String,
    pub direction: SortDirection,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum SortDirection {
    Asc,
    Desc,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq, Eq)]
pub struct TableFilterClause {
    pub column: String,
    pub operator: TableFilterOperator,
    /// User-entered scalar value. Null checks intentionally use operators
    /// instead of overloading this field.
    pub value: Option<String>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Type, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TableFilterOperator {
    Equals,
    NotEquals,
    Contains,
    IsNull,
    IsNotNull,
    GreaterThan,
    GreaterThanOrEqual,
    LessThan,
    LessThanOrEqual,
}
