
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listConnections() : Promise<Result<ConnectionConfig[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveConnection(config: ConnectionConfig, password: string | null) : Promise<Result<ConnectionConfig, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_connection", { config, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteConnection(id: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testConnection(config: ConnectionConfig, password: string | null) : Promise<Result<DriverInfo, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_connection", { config, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connect(id: string) : Promise<Result<DriverInfo, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reconnect(id: string) : Promise<Result<DriverInfo, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconnect", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disconnect(id: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async introspect(connectionId: string, refresh: boolean | null) : Promise<Result<Database[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("introspect", { connectionId, refresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runQuery(connectionId: string, sql: string, maxRows: number | null, offset: number | null, database: string | null, tabId: string | null, queryId: string | null) : Promise<Result<QueryResult, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_query", { connectionId, sql, maxRows, offset, database, tabId, queryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel a running query previously started through [`run_query`] with a
 * `query_id`. Returns `true` when a running statement was found and
 * signalled, `false` when it had already finished.
 */
async cancelQuery(connectionId: string, queryId: string) : Promise<Result<boolean, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_query", { connectionId, queryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async explainQuery(connectionId: string, sql: string, mode: PlanMode, database: string | null) : Promise<Result<QueryPlan, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("explain_query", { connectionId, sql, mode, database }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async browseTable(request: TableBrowseRequest) : Promise<Result<QueryResult, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browse_table", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewTableChanges(request: TableChangeRequest) : Promise<Result<TableCommitPreview, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_table_changes", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async commitTableChanges(connectionId: string, request: TableChangeRequest, tabId: string | null) : Promise<Result<TableCommitResult, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_table_changes", { connectionId, request, tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compare `source` against `target`, returning the render-ready diff and the
 * migration statements that transform source into target.
 */
async compareSchemas(source: SchemaSource, target: SchemaSource) : Promise<Result<SchemaComparison, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compare_schemas", { source, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Assemble the user's selected statements into a single runnable script.
 * Kept in Rust so transaction wrapping stays dialect-aware and the frontend
 * never hand-builds executable SQL.
 */
async buildMigrationScript(statements: MigrationStatement[], wrapInTransaction: boolean) : Promise<string> {
    return await TAURI_INVOKE("build_migration_script", { statements, wrapInTransaction });
},
/**
 * Apply a reviewed (and possibly hand-edited) migration script against
 * `database` on the open connection. Logged to query history like any other
 * executed statement.
 */
async applyMigration(connectionId: string, database: string, sql: string, tabId: string | null) : Promise<Result<MigrationApplyResult, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_migration", { connectionId, database, sql, tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Capture a live database's schema tree to `~/.cellar/snapshots/`.
 */
async saveSchemaSnapshot(connectionId: string, database: string) : Promise<Result<SchemaSnapshotMeta, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_schema_snapshot", { connectionId, database }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List saved snapshots, newest first.
 */
async listSchemaSnapshots() : Promise<Result<SchemaSnapshotMeta[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_schema_snapshots") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSchemaSnapshot(id: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_schema_snapshot", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listQueryHistory(connectionId: string | null, database: string | null, tabId: string | null, search: string | null, limit: number | null) : Promise<Result<QueryHistoryRecord[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_query_history", { connectionId, database, tabId, search, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the API key for `provider` in the OS keychain, overwriting any
 * existing entry.
 */
async aiStoreKey(provider: string, key: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_store_key", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the stored API key for `provider`. Returns `None` when nothing is
 * stored, which is distinct from a keychain failure.
 */
async aiLoadKey(provider: string) : Promise<Result<string | null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_load_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove the stored API key for `provider`. A no-op if none exists.
 */
async aiDeleteKey(provider: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_delete_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Report whether a key is stored for `provider` without returning it — used by
 * settings to show "configured" state.
 */
async aiHasKey(provider: string) : Promise<Result<boolean, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_has_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CellAssignment = { column: string; value: DiffValue }
/**
 * One cell value, tagged so the frontend can render the right editor and
 * preserve type fidelity through the IPC boundary.
 * 
 * `Numeric` is intentionally a `String`: Postgres `numeric` has arbitrary
 * precision and JavaScript `number` does not. Drivers that decode it as a
 * float would lose digits, so we round-trip it as text.
 */
export type CellValue = { type: "Null" } | { type: "Bool"; value: boolean } | { type: "Int"; value: number } | { type: "Float"; value: number } | 
/**
 * Arbitrary-precision decimal as a string to preserve precision.
 */
{ type: "Numeric"; value: string } | { type: "Text"; value: string } | { type: "Bytes"; value: number[] } | { type: "Json"; value: JsonValue } | { type: "Uuid"; value: string } | 
/**
 * Calendar date with no timezone.
 */
{ type: "Date"; value: string } | 
/**
 * Wall-clock time with no date or timezone.
 */
{ type: "Time"; value: string } | 
/**
 * Local timestamp without a timezone (Postgres `timestamp`).
 */
{ type: "Timestamp"; value: string } | 
/**
 * Absolute timestamp with UTC offset (Postgres `timestamptz`).
 */
{ type: "TimestampTz"; value: string }
/**
 * Typed error surface for every public API in `cellar-core` and driver crates.
 * 
 * Crossing the IPC boundary requires serializable values, so the error is a
 * closed enum rather than a string. Drivers map their native errors into one
 * of these variants and stash the original message in `detail`.
 */
export type CellarError = { kind: "Connection"; detail: string } | { kind: "Authentication"; detail: string } | { kind: "Tls"; detail: string } | { kind: "Query"; detail: string } | { kind: "Introspection"; detail: string } | { kind: "UnsupportedType"; detail: string } | { kind: "Decode"; detail: string } | { kind: "Timeout"; detail: string } | { kind: "NotConnected"; detail: string } | { kind: "InvalidConfig"; detail: string } | { kind: "Io"; detail: string } | { kind: "Internal"; detail: string }
/**
 * Per-object classification in a schema comparison.
 */
export type ChangeStatus = 
/**
 * Present in target but not source — a `CREATE`/`ADD` candidate.
 */
"added" | 
/**
 * Present in source but not target — a `DROP` candidate.
 */
"removed" | 
/**
 * Present in both, but the definitions differ.
 */
"modified" | 
/**
 * Present in both and identical.
 */
"unchanged"
export type Column = { name: string; 
/**
 * The engine-native type name as reported by the catalog (e.g. `int4`,
 * `varchar(64)`). Drivers must not normalize this — the UI relies on the
 * raw type to render badges and pick the right editor.
 */
data_type: string; nullable: boolean; default: string | null; is_primary_key: boolean; ordinal: number; comment: string | null }
export type ColumnDiff = { name: string; status: ChangeStatus; source: Column | null; target: Column | null; 
/**
 * Human-readable field-level changes when `status == Modified`
 * (e.g. `type int4 → bigint`, `set NOT NULL`).
 */
changes: string[] }
/**
 * Lightweight column descriptor for a query result. The full structural
 * schema lives in [`crate::schema::Column`]; this only carries what the grid
 * needs to render headers.
 */
export type ColumnMeta = { name: string; 
/**
 * The engine-native type name (e.g. `int4`, `text`, `jsonb`).
 */
data_type: string; 
/**
 * Whether the column came back as a known nullable position. Result-set
 * columns are nullable by default — drivers can sharpen this where they
 * can prove non-null.
 */
nullable: boolean }
/**
 * Inputs required to open a connection. Passwords never live here — they
 * come out of [`cellar-secrets`](../cellar_secrets) at connect time.
 */
export type ConnectionConfig = { id: string; name: string; engine: Engine; host: string; port: number; database: string; user: string; ssl_mode: SslMode; env_tag: EnvTag | null; application_name: string | null; 
/**
 * Color swatch used by the sidebar accent strip; opaque hex like `#4f8ff7`.
 */
color: string | null }
/**
 * One database visible to the connected user. For Postgres this maps to a
 * `pg_database` row, for MySQL to a single catalog, for SQLite the file.
 */
export type Database = { name: string; is_default: boolean; schemas: Schema[] }
export type DatabaseNotice = { severity: NoticeSeverity; 
/**
 * Engine-native code when available. For Postgres this is the SQLSTATE.
 */
code: string | null; message: string; detail: string | null; hint: string | null; 
/**
 * RFC 3339 timestamp generated by the host when it observes the notice.
 */
timestamp: string; connection_id: string | null; database: string | null; query_id: string | null }
export type DiffColumn = { name: string; data_type: string; nullable: boolean }
/**
 * Aggregate counts, used for the comparison header without re-walking the
 * tree on the frontend.
 */
export type DiffSummary = { tables_added: number; tables_removed: number; tables_modified: number; tables_unchanged: number; views_added: number; views_removed: number; views_modified: number; views_unchanged: number }
export type DiffValue = { value: string | null }
export type DriverInfo = { engine: Engine; 
/**
 * Server version as reported by the engine, e.g. `PostgreSQL 16.2 on
 * x86_64-linux-gnu`.
 */
version: string }
/**
 * User-facing identifier for which driver to load. Lives in connection
 * configs and crosses IPC, so it has to be serializable.
 */
export type Engine = "postgres" | "mysql" | "sqlite" | "mssql" | "azure" | "firestore"
/**
 * Environment tag, per SPEC §6.1. Production-tagged connections get red
 * styling and confirmation guardrails — this PR wires the data, not the UX.
 */
export type EnvTag = "local" | "dev" | "staging" | "prod"
export type ForeignKey = { name: string; columns: string[]; referenced_schema: string; referenced_table: string; referenced_columns: string[] }
export type ForeignKeyDiff = { name: string; status: ChangeStatus; source: ForeignKey | null; target: ForeignKey | null }
export type Index = { name: string; columns: string[]; unique: boolean; primary: boolean }
export type IndexDiff = { name: string; status: ChangeStatus; source: Index | null; target: Index | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type MigrationApplyResult = { duration_ms: number }
/**
 * What a single migration statement does. Drives grouping/iconography in the
 * UI and the destructive-confirmation gate.
 */
export type MigrationKind = "create-table" | "drop-table" | "add-column" | "drop-column" | "alter-column" | "alter-primary-key" | "create-index" | "drop-index" | "add-foreign-key" | "drop-foreign-key" | "create-view" | "replace-view" | "drop-view"
/**
 * One reviewable, individually selectable unit of the migration. `sql` may
 * span multiple physical statements (e.g. drop-then-add a constraint) but is
 * one logical change the user toggles together.
 */
export type MigrationStatement = { 
/**
 * Stable id (`kind:object`) the frontend uses for selection state.
 */
id: string; kind: MigrationKind; 
/**
 * Qualified object the statement targets, for display.
 */
object: string; description: string; 
/**
 * `true` for statements that drop objects or can lose data — gated behind
 * explicit confirmation in the UI.
 */
destructive: boolean; sql: string }
export type NoticeCapture = { supported: boolean; reason: string | null }
export type NoticeSeverity = "panic" | "fatal" | "error" | "warning" | "notice" | "info" | "log" | "debug" | "unknown"
export type PlanDetail = { label: string; value: string }
/**
 * Whether an execution plan should only estimate the plan or run the
 * statement to collect actual timings. `Analyze` is intentionally explicit:
 * Postgres `EXPLAIN ANALYZE` executes the supplied SQL.
 */
export type PlanMode = "estimate" | "analyze"
export type PlanNode = { node_type: string; relation_name: string | null; schema_name: string | null; alias: string | null; index_name: string | null; join_type: string | null; startup_cost: number | null; total_cost: number | null; plan_rows: number | null; plan_width: number | null; actual_startup_time_ms: number | null; actual_total_time_ms: number | null; actual_rows: number | null; actual_loops: number | null; details: PlanDetail[]; children: PlanNode[] }
export type PrimaryKeyDiff = { status: ChangeStatus; source: string[]; target: string[] }
export type QueryHistoryRecord = { id: number; connection_id: string; connection_name: string | null; tab_id: string | null; database: string | null; sql: string; executed_at_ms: number; duration_ms: number; success: boolean; row_count: number | null; truncated: boolean; error_summary: string | null }
export type QueryPlan = { mode: PlanMode; engine: string; database: string | null; sql: string; root: PlanNode; planning_time_ms: number | null; execution_time_ms: number | null; duration_ms: number; 
/**
 * Original engine plan payload for advanced inspection and future richer
 * renderers. The typed tree above is the stable UI contract.
 */
raw_json: JsonValue }
export type QueryResult = { columns: ColumnMeta[]; rows: CellValue[][]; 
/**
 * Database-emitted notices captured while executing this query. Host-side
 * warnings, validation messages, and truncation badges belong in the
 * Messages panel, not here.
 */
notices: DatabaseNotice[]; 
/**
 * Whether the current driver path can observe server notice frames.
 */
notice_capture: NoticeCapture; 
/**
 * Server-reported affected-row count for DML, or `None` for SELECT-like
 * statements where it isn't meaningful.
 */
rows_affected: number | null; 
/**
 * Total elapsed time for the round-trip, measured in the host.
 */
duration_ms: number; 
/**
 * `true` when the driver truncated the result because it hit
 * [`Query::max_rows`]. The grid uses this to show a "+ more" badge.
 */
truncated: boolean; 
/**
 * Total row count for the underlying dataset, when the driver can provide
 * it cheaply. `None` means "unknown" — the UI shows `truncated` alone.
 * For table browse with `include_total: true` the driver runs a
 * `SELECT count(*)` with the same filter clauses and returns it here.
 * Free-form queries always return `None`.
 */
total_rows: number | null }
export type RowChange = { kind: "update"; row_id: string; keys: CellAssignment[]; edits: CellAssignment[] } | { kind: "insert"; row_id: string; values: CellAssignment[] } | { kind: "delete"; row_id: string; keys: CellAssignment[] }
export type Schema = { name: string; tables: Table[]; views: View[] }
/**
 * Bundled output of a comparison: the render-ready diff tree plus the
 * migration statements that transform source into target. Returned by the
 * `compare_schemas` IPC command so the UI gets both in one round-trip.
 */
export type SchemaComparison = { diff: SchemaDiff; statements: MigrationStatement[] }
/**
 * Top-level result of comparing a `source` schema against a `target` schema.
 */
export type SchemaDiff = { source_label: string; target_label: string; source_schema: string; target_schema: string; tables: TableDiff[]; views: ViewDiff[]; summary: DiffSummary }
/**
 * Lightweight descriptor listed in the snapshot picker without loading the
 * full schema tree from disk.
 */
export type SchemaSnapshotMeta = { id: string; label: string; engine: string; connection_id: string; connection_name: string; database: string; 
/**
 * Schema names captured, so the picker can offer a namespace to compare.
 */
schemas: string[]; table_count: number; 
/**
 * Unix epoch milliseconds when the snapshot was saved.
 */
created_at_ms: number }
/**
 * One side of a comparison. A schema either comes from a live connection
 * (introspected fresh) or from a saved snapshot on disk.
 */
export type SchemaSource = { kind: "live"; connection_id: string; database: string; schema: string; label: string | null } | { kind: "snapshot"; id: string; schema: string; label: string | null }
export type SortDirection = "asc" | "desc"
export type SslMode = "disable" | "prefer" | "require" | "verify-ca" | "verify-full"
export type Table = { name: string; schema: string; 
/**
 * `None` until lazy row-count introspection has run.
 */
row_count: number | null; columns: Column[]; primary_key: string[]; foreign_keys: ForeignKey[]; indexes: Index[] }
/**
 * Typed request for browsing one table through the grid. This deliberately
 * does not carry executable SQL; each driver owns safe dialect-specific
 * rendering and value binding.
 */
export type TableBrowseRequest = { connection_id: string; database: string | null; schema: string; table: string; limit: number | null; 
/**
 * Zero-based row offset for page-style table browsing. Drivers should
 * combine this with deterministic ordering when available so table tabs
 * stay stable as users move between pages.
 */
offset: number | null; sorts: TableSortClause[]; filters: TableFilterClause[]; 
/**
 * When no explicit sort is requested, order by the table primary key if
 * metadata is available. This keeps table tabs stable without the UI
 * building an `ORDER BY` string.
 */
primary_key_fallback_ordering: boolean; 
/**
 * When `true`, the driver additionally runs `SELECT count(*)` with the
 * same filter clauses and returns the result in `QueryResult.total_rows`.
 * Defaults to `false` to avoid the extra round-trip on every page flip.
 * Callers should set this on the first page load of a table tab.
 */
include_total?: boolean }
export type TableChangeRequest = { database: string | null; schema: string; table: string; primary_key: string[]; columns: DiffColumn[]; changes: RowChange[] }
export type TableCommitPreview = { sql: string; expected_rows: number; statement_count: number }
export type TableCommitResult = { sql: string; rows_affected: number; duration_ms: number }
export type TableDiff = { name: string; status: ChangeStatus; columns: ColumnDiff[]; indexes: IndexDiff[]; foreign_keys: ForeignKeyDiff[]; primary_key: PrimaryKeyDiff; 
/**
 * Full source/target objects so the UI can render either side verbatim.
 */
source: Table | null; target: Table | null }
export type TableFilterClause = { column: string; operator: TableFilterOperator; 
/**
 * User-entered scalar value. Null checks intentionally use operators
 * instead of overloading this field.
 */
value: string | null }
export type TableFilterOperator = "equals" | "not_equals" | "contains" | "is_null" | "is_not_null" | "greater_than" | "greater_than_or_equal" | "less_than" | "less_than_or_equal"
export type TableSortClause = { column: string; direction: SortDirection }
export type View = { name: string; schema: string; columns: Column[]; definition: string | null }
export type ViewDiff = { name: string; status: ChangeStatus; source: View | null; target: View | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
