
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listConnections() : Promise<Result<ConnectionConfig[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveConnection(config: ConnectionConfig, password: string | null) : Promise<Result<ConnectionConfig, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_connection", { config, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteConnection(id: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testConnection(config: ConnectionConfig, password: string | null) : Promise<Result<DriverInfo, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_connection", { config, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connect(id: string) : Promise<Result<DriverInfo, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reconnect(id: string) : Promise<Result<DriverInfo, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconnect", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disconnect(id: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan the local machine for DataGrip data sources and return the connections
 * we can map. Read-only — nothing is saved; the frontend lets the user pick
 * which to import and supply passwords (DataGrip never exposes those).
 */
async importDatagrip() : Promise<Result<DatagripImport, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_datagrip") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async introspect(connectionId: string, refresh: boolean | null) : Promise<Result<Database[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("introspect", { connectionId, refresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Find every view, function, procedure, trigger, and constraint that
 * references `object_name` (optionally narrowed to `column_name`). Scoped to
 * `schema` within `database` by default; set `all_schemas` to search the whole
 * database. References are confirmed structurally, never by substring match.
 */
async findUsages(connectionId: string, database: string | null, schema: string, objectName: string, columnName: string | null, allSchemas: boolean | null) : Promise<Result<UsageReference[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_usages", { connectionId, database, schema, objectName, columnName, allSchemas }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build the foreign-key graph for the ER diagram view. Reuses the cached
 * introspection tree (so it never re-hits the server when the schema is warm)
 * and derives the graph in [`cellar_core::er`]. `schemas` scopes the graph to
 * a subset of schemas; `None` includes them all.
 */
async erGraph(connectionId: string, database: string, schemas: string[] | null) : Promise<Result<ErGraph, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("er_graph", { connectionId, database, schemas }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runQuery(connectionId: string, sql: string, maxRows: number | null, offset: number | null, database: string | null, tabId: string | null, queryId: string | null, params: QueryParam[] | null) : Promise<Result<QueryResult, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_query", { connectionId, sql, maxRows, offset, database, tabId, queryId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runReadOnlyQuery(connectionId: string, sql: string, maxRows: number | null, database: string | null) : Promise<Result<QueryResult, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_read_only_query", { connectionId, sql, maxRows, database }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel a running query previously started through [`run_query`] with a
 * `query_id`. Returns `true` when a running statement was found and
 * signalled, `false` when it had already finished.
 */
async cancelQuery(connectionId: string, queryId: string) : Promise<Result<boolean, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_query", { connectionId, queryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async explainQuery(connectionId: string, sql: string, mode: PlanMode, database: string | null) : Promise<Result<QueryPlan, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("explain_query", { connectionId, sql, mode, database }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect named (`:name`) and positional (`$N`) parameter placeholders in a
 * statement so the editor can collect values before running it. Pure parsing
 * via `cellar-sql`; no connection is required.
 */
async detectQueryParameters(sql: string, engine: Engine) : Promise<Result<DetectedParameter[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_query_parameters", { sql, engine }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async browseTable(request: TableBrowseRequest) : Promise<Result<QueryResult, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browse_table", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewTableChanges(connectionId: string, request: TableChangeRequest) : Promise<Result<TableCommitPreview, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_table_changes", { connectionId, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async commitTableChanges(connectionId: string, request: TableChangeRequest, tabId: string | null) : Promise<Result<TableCommitResult, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_table_changes", { connectionId, request, tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Commit a CSV import. Same transactional + history path as
 * `commit_table_changes`, but tolerant of idempotent no-op rows.
 */
async commitTableImport(connectionId: string, request: TableChangeRequest, tabId: string | null) : Promise<Result<TableCommitResult, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_table_import", { connectionId, request, tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compare `source` against `target`, returning the render-ready diff and the
 * migration statements that transform source into target.
 */
async compareSchemas(source: SchemaSource, target: SchemaSource) : Promise<Result<SchemaComparison, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compare_schemas", { source, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Assemble the user's selected statements into a single runnable script.
 * Kept in Rust so transaction wrapping stays dialect-aware and the frontend
 * never hand-builds executable SQL. The `dialect` comes from the comparison
 * (the source engine) so the transaction wrap matches that engine's DDL
 * semantics rather than always assuming Postgres.
 */
async buildMigrationScript(statements: MigrationStatement[], dialect: Dialect, wrapInTransaction: boolean) : Promise<string> {
    return await TAURI_INVOKE("build_migration_script", { statements, dialect, wrapInTransaction });
},
/**
 * Apply a reviewed (and possibly hand-edited) migration script against
 * `database` on the open connection. Logged to query history like any other
 * executed statement.
 */
async applyMigration(connectionId: string, database: string, sql: string, tabId: string | null) : Promise<Result<MigrationApplyResult, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_migration", { connectionId, database, sql, tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Capture a live database's schema tree to `~/.cellar/snapshots/`.
 */
async saveSchemaSnapshot(connectionId: string, database: string) : Promise<Result<SchemaSnapshotMeta, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_schema_snapshot", { connectionId, database }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List saved snapshots, newest first.
 */
async listSchemaSnapshots() : Promise<Result<SchemaSnapshotMeta[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_schema_snapshots") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSchemaSnapshot(id: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_schema_snapshot", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listQueryHistory(connectionId: string | null, database: string | null, tabId: string | null, search: string | null, limit: number | null) : Promise<Result<QueryHistoryRecord[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_query_history", { connectionId, database, tabId, search, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List every saved template, sorted by name. Missing directory ⇒ empty list.
 */
async listQueryTemplates() : Promise<Result<QueryTemplate[], CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_query_templates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save (create or overwrite) a template. Returns the stored template.
 */
async saveQueryTemplate(template: QueryTemplate) : Promise<Result<QueryTemplate, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_query_template", { template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the template whose name slugifies to `name`'s file.
 */
async deleteQueryTemplate(name: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_query_template", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the API key for `provider` in the OS keychain, overwriting any
 * existing entry.
 */
async aiStoreKey(provider: string, key: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_store_key", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the stored API key for `provider`. Returns `None` when nothing is
 * stored, which is distinct from a keychain failure.
 */
async aiLoadKey(provider: string) : Promise<Result<string | null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_load_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove the stored API key for `provider`. A no-op if none exists.
 */
async aiDeleteKey(provider: string) : Promise<Result<null, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_delete_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Report whether a key is stored for `provider` without returning it — used by
 * settings to show "configured" state.
 */
async aiHasKey(provider: string) : Promise<Result<boolean, CellarError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_has_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CellAssignment = { column: string; value: DiffValue }
/**
 * One cell value, tagged so the frontend can render the right editor and
 * preserve type fidelity through the IPC boundary.
 * 
 * `Numeric` is intentionally a `String`: Postgres `numeric` has arbitrary
 * precision and JavaScript `number` does not. Drivers that decode it as a
 * float would lose digits, so we round-trip it as text.
 */
export type CellValue = { type: "Null" } | { type: "Bool"; value: boolean } | { type: "Int"; value: number } | { type: "Float"; value: number } | 
/**
 * Arbitrary-precision decimal as a string to preserve precision.
 */
{ type: "Numeric"; value: string } | { type: "Text"; value: string } | { type: "Bytes"; value: number[] } | { type: "Json"; value: JsonValue } | { type: "Uuid"; value: string } | 
/**
 * Calendar date with no timezone.
 */
{ type: "Date"; value: string } | 
/**
 * Wall-clock time with no date or timezone.
 */
{ type: "Time"; value: string } | 
/**
 * Local timestamp without a timezone (Postgres `timestamp`).
 */
{ type: "Timestamp"; value: string } | 
/**
 * Absolute timestamp with UTC offset (Postgres `timestamptz`).
 */
{ type: "TimestampTz"; value: string }
/**
 * Typed error surface for every public API in `cellar-core` and driver crates.
 * 
 * Crossing the IPC boundary requires serializable values, so the error is a
 * closed enum rather than a string. Drivers map their native errors into one
 * of these variants and stash the original message in `detail`.
 */
export type CellarError = { kind: "Connection"; detail: string } | { kind: "Authentication"; detail: string } | { kind: "Tls"; detail: string } | { kind: "Query"; detail: string } | { kind: "Introspection"; detail: string } | { kind: "UnsupportedType"; detail: string } | { kind: "Decode"; detail: string } | { kind: "Timeout"; detail: string } | { kind: "NotConnected"; detail: string } | { kind: "InvalidConfig"; detail: string } | { kind: "Io"; detail: string } | { kind: "Internal"; detail: string }
/**
 * Per-object classification in a schema comparison.
 */
export type ChangeStatus = 
/**
 * Present in target but not source — a `CREATE`/`ADD` candidate.
 */
"added" | 
/**
 * Present in source but not target — a `DROP` candidate.
 */
"removed" | 
/**
 * Present in both, but the definitions differ.
 */
"modified" | 
/**
 * Present in both and identical.
 */
"unchanged"
export type Column = { name: string; 
/**
 * The engine-native type name as reported by the catalog (e.g. `int4`,
 * `varchar(64)`). Drivers must not normalize this — the UI relies on the
 * raw type to render badges and pick the right editor.
 */
data_type: string; nullable: boolean; default: string | null; is_primary_key: boolean; ordinal: number; comment: string | null }
export type ColumnDiff = { name: string; status: ChangeStatus; source: Column | null; target: Column | null; 
/**
 * Human-readable field-level changes when `status == Modified`
 * (e.g. `type int4 → bigint`, `set NOT NULL`).
 */
changes: string[] }
/**
 * Lightweight column descriptor for a query result. The full structural
 * schema lives in [`crate::schema::Column`]; this only carries what the grid
 * needs to render headers.
 */
export type ColumnMeta = { name: string; 
/**
 * The engine-native type name (e.g. `int4`, `text`, `jsonb`).
 */
data_type: string; 
/**
 * Whether the column came back as a known nullable position. Result-set
 * columns are nullable by default — drivers can sharpen this where they
 * can prove non-null.
 */
nullable: boolean }
/**
 * Inputs required to open a connection. Passwords never live here — they
 * come out of [`cellar-secrets`](../cellar_secrets) at connect time.
 */
export type ConnectionConfig = { id: string; name: string; engine: Engine; host: string; port: number; database: string; user: string; ssl_mode: SslMode; env_tag: EnvTag | null; application_name: string | null; 
/**
 * Color swatch used by the sidebar accent strip; opaque hex like `#4f8ff7`.
 */
color: string | null }
/**
 * One database visible to the connected user. For Postgres this maps to a
 * `pg_database` row, for MySQL to a single catalog, for SQLite the file.
 */
export type Database = { name: string; is_default: boolean; schemas: Schema[] }
export type DatabaseNotice = { severity: NoticeSeverity; 
/**
 * Engine-native code when available. For Postgres this is the SQLSTATE.
 */
code: string | null; message: string; detail: string | null; hint: string | null; 
/**
 * RFC 3339 timestamp generated by the host when it observes the notice.
 */
timestamp: string; connection_id: string | null; database: string | null; query_id: string | null }
/**
 * Result of scanning DataGrip for importable connections.
 */
export type DatagripImport = { 
/**
 * Connections we could map. Passwords are never included — the caller
 * collects them separately (import-time form or on first connect).
 */
connections: ConnectionConfig[]; 
/**
 * Data sources we found but could not import, each with a human reason
 * (unsupported engine, unparseable URL). Surfaced so the import is honest
 * about what it dropped rather than silently skipping rows.
 */
skipped: string[] }
/**
 * A placeholder detected in a SQL statement. The frontend uses this to render
 * a labeled input before running the query.
 */
export type DetectedParameter = { 
/**
 * Parameter name without its sigil (`user_id` for `:user_id`, `1` for
 * `$1`). Distinct names appear once; a name reused in the statement is
 * reported a single time.
 */
name: string; 
/**
 * The placeholder exactly as it appears in the SQL (`:user_id`, `$1`).
 */
placeholder: string; style: ParameterStyle; 
/**
 * 1-based bind position in the order the distinct names first appear.
 */
ordinal: number; 
/**
 * Best-effort column the placeholder is compared against (`id` for
 * `WHERE id = :id`), so the UI can infer an input type from schema.
 * `None` when no simple comparison was detected.
 */
column_hint: string | null }
/**
 * SQL dialect a statement is being generated for. Identifier quoting and a
 * handful of DDL spellings differ per engine; everything that varies routes
 * through [`Dialect`] so callers stay engine-agnostic.
 */
export type Dialect = "postgres" | "mysql" | "sqlite" | "mssql"
export type DiffColumn = { name: string; data_type: string; nullable: boolean }
/**
 * Aggregate counts, used for the comparison header without re-walking the
 * tree on the frontend.
 */
export type DiffSummary = { tables_added: number; tables_removed: number; tables_modified: number; tables_unchanged: number; views_added: number; views_removed: number; views_modified: number; views_unchanged: number }
export type DiffValue = { value: string | null }
export type DriverInfo = { engine: Engine; 
/**
 * Server version as reported by the engine, e.g. `PostgreSQL 16.2 on
 * x86_64-linux-gnu`.
 */
version: string }
/**
 * User-facing identifier for which driver to load. Lives in connection
 * configs and crosses IPC, so it has to be serializable.
 */
export type Engine = "postgres" | "mysql" | "sqlite" | "mssql" | "azure" | "firestore" | "convex" | "cosmos" | "supabase" | "neon" | "planetscale"
/**
 * Environment tag, per SPEC §6.1. Production-tagged connections get red
 * styling and confirmation guardrails — this PR wires the data, not the UX.
 */
export type EnvTag = "local" | "dev" | "staging" | "prod"
/**
 * A column rendered inside an ER node. Carries just enough for the diagram:
 * name, type, and key-role badges.
 */
export type ErColumn = { name: string; data_type: string; nullable: boolean; is_primary_key: boolean; 
/**
 * `true` when the column participates in at least one outgoing foreign key.
 */
is_foreign_key: boolean }
/**
 * A foreign-key relationship, drawn as an edge from the referencing table to
 * the referenced table.
 */
export type ErEdge = { 
/**
 * Stable id derived from the endpoints and constraint name.
 */
id: string; constraint_name: string; 
/**
 * `"schema.table"` of the table that holds the FK columns.
 */
source: string; 
/**
 * `"schema.table"` of the referenced table.
 */
target: string; source_columns: string[]; target_columns: string[] }
/**
 * The full graph for one database, scoped to a selection of schemas.
 */
export type ErGraph = { database: string; 
/**
 * Schema names present in this graph, sorted — drives the show/hide UI.
 */
schemas: string[]; nodes: ErNode[]; edges: ErEdge[] }
/**
 * One table in the diagram. `id` is `"schema.table"`; edges reference nodes by
 * this id.
 */
export type ErNode = { id: string; schema: string; name: string; columns: ErColumn[]; primary_key: string[]; row_count: number | null }
export type ForeignKey = { name: string; columns: string[]; referenced_schema: string; referenced_table: string; referenced_columns: string[] }
export type ForeignKeyDiff = { name: string; status: ChangeStatus; source: ForeignKey | null; target: ForeignKey | null }
export type Index = { name: string; columns: string[]; unique: boolean; primary: boolean }
export type IndexDiff = { name: string; status: ChangeStatus; source: Index | null; target: Index | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type MigrationApplyResult = { duration_ms: number }
/**
 * What a single migration statement does. Drives grouping/iconography in the
 * UI and the destructive-confirmation gate.
 */
export type MigrationKind = "create-table" | "drop-table" | "add-column" | "drop-column" | "alter-column" | "alter-primary-key" | "create-index" | "drop-index" | "add-foreign-key" | "drop-foreign-key" | "create-view" | "replace-view" | "drop-view"
/**
 * One reviewable, individually selectable unit of the migration. `sql` may
 * span multiple physical statements (e.g. drop-then-add a constraint) but is
 * one logical change the user toggles together.
 */
export type MigrationStatement = { 
/**
 * Stable id (`kind:object`) the frontend uses for selection state.
 */
id: string; kind: MigrationKind; 
/**
 * Qualified object the statement targets, for display.
 */
object: string; description: string; 
/**
 * `true` for statements that drop objects or can lose data — gated behind
 * explicit confirmation in the UI.
 */
destructive: boolean; sql: string }
export type NoticeCapture = { supported: boolean; reason: string | null }
export type NoticeSeverity = "panic" | "fatal" | "error" | "warning" | "notice" | "info" | "log" | "debug" | "unknown"
/**
 * Whether a detected placeholder was written as a named (`:name`) or
 * positional (`$N`) parameter.
 */
export type ParameterStyle = "named" | "positional"
export type PlanDetail = { label: string; value: string }
/**
 * Whether an execution plan should only estimate the plan or run the
 * statement to collect actual timings. `Analyze` is intentionally explicit:
 * Postgres `EXPLAIN ANALYZE` executes the supplied SQL.
 */
export type PlanMode = "estimate" | "analyze"
export type PlanNode = { node_type: string; relation_name: string | null; schema_name: string | null; alias: string | null; index_name: string | null; join_type: string | null; startup_cost: number | null; total_cost: number | null; plan_rows: number | null; plan_width: number | null; actual_startup_time_ms: number | null; actual_total_time_ms: number | null; actual_rows: number | null; actual_loops: number | null; details: PlanDetail[]; children: PlanNode[] }
export type PrimaryKeyDiff = { status: ChangeStatus; source: string[]; target: string[] }
export type QueryHistoryRecord = { id: number; connection_id: string; connection_name: string | null; tab_id: string | null; database: string | null; sql: string; executed_at_ms: number; duration_ms: number; success: boolean; row_count: number | null; truncated: boolean; error_summary: string | null }
/**
 * One bound parameter value supplied by the caller. Carries a typed
 * [`CellValue`] so the driver can bind it through the native protocol with the
 * right wire type instead of stringifying it.
 */
export type QueryParam = { 
/**
 * Parameter name without its sigil. For `:user_id` this is `user_id`; for
 * `$1` this is `1`.
 */
name: string; value: CellValue }
export type QueryPlan = { mode: PlanMode; engine: string; database: string | null; sql: string; root: PlanNode; planning_time_ms: number | null; execution_time_ms: number | null; duration_ms: number; 
/**
 * Original engine plan payload for advanced inspection and future richer
 * renderers. The typed tree above is the stable UI contract.
 */
raw_json: JsonValue }
export type QueryResult = { columns: ColumnMeta[]; rows: CellValue[][]; 
/**
 * Database-emitted notices captured while executing this query. Host-side
 * warnings, validation messages, and truncation badges belong in the
 * Messages panel, not here.
 */
notices: DatabaseNotice[]; 
/**
 * Whether the current driver path can observe server notice frames.
 */
notice_capture: NoticeCapture; 
/**
 * Server-reported affected-row count for DML, or `None` for SELECT-like
 * statements where it isn't meaningful.
 */
rows_affected: number | null; 
/**
 * Total elapsed time for the round-trip, measured in the host.
 */
duration_ms: number; 
/**
 * `true` when the driver truncated the result because it hit
 * [`Query::max_rows`]. The grid uses this to show a "+ more" badge.
 */
truncated: boolean; 
/**
 * Total row count for the underlying dataset, when the driver can provide
 * it cheaply. `None` means "unknown" — the UI shows `truncated` alone.
 * For table browse with `include_total: true` the driver runs a
 * `SELECT count(*)` with the same filter clauses and returns it here.
 * Free-form queries always return `None`.
 */
total_rows: number | null }
/**
 * A saved (optionally parameterized) query. `name` is the stable identifier;
 * saving a template whose name slugifies to an existing file overwrites it.
 */
export type QueryTemplate = { name: string; description: string; sql: string }
export type RowChange = { kind: "update"; row_id: string; keys: CellAssignment[]; edits: CellAssignment[] } | { kind: "insert"; row_id: string; values: CellAssignment[] } | { kind: "delete"; row_id: string; keys: CellAssignment[] } | 
/**
 * Insert a full row, resolving collisions on `conflict_columns` (a unique
 * or primary key) by updating `update_columns` from the proposed values.
 * An empty `update_columns` compiles to `ON CONFLICT ... DO NOTHING`
 * (insert-only / skip duplicates). The DB decides per row whether it is an
 * insert or an update, so there is no read-then-write race. Used by the
 * CSV import wizard for its insert-only and upsert modes.
 */
{ kind: "upsert"; row_id: string; conflict_columns: string[]; values: CellAssignment[]; update_columns: string[] }
export type Schema = { name: string; tables: Table[]; views: View[] }
/**
 * Bundled output of a comparison: the render-ready diff tree, the migration
 * statements that transform source into target, and the dialect the DDL was
 * generated for. Returned by the `compare_schemas` IPC command so the UI gets
 * everything (including the dialect to round-trip back into script assembly)
 * in one call.
 */
export type SchemaComparison = { diff: SchemaDiff; statements: MigrationStatement[]; dialect: Dialect }
/**
 * Top-level result of comparing a `source` schema against a `target` schema.
 */
export type SchemaDiff = { source_label: string; target_label: string; source_schema: string; target_schema: string; tables: TableDiff[]; views: ViewDiff[]; summary: DiffSummary }
/**
 * Lightweight descriptor listed in the snapshot picker without loading the
 * full schema tree from disk.
 */
export type SchemaSnapshotMeta = { id: string; label: string; engine: string; connection_id: string; connection_name: string; database: string; 
/**
 * Schema names captured, so the picker can offer a namespace to compare.
 */
schemas: string[]; table_count: number; 
/**
 * Unix epoch milliseconds when the snapshot was saved.
 */
created_at_ms: number }
/**
 * One side of a comparison. A schema either comes from a live connection
 * (introspected fresh) or from a saved snapshot on disk.
 */
export type SchemaSource = { kind: "live"; connection_id: string; database: string; schema: string; label: string | null } | { kind: "snapshot"; id: string; schema: string; label: string | null }
export type SortDirection = "asc" | "desc"
export type SslMode = "disable" | "prefer" | "require" | "verify-ca" | "verify-full"
export type Table = { name: string; schema: string; 
/**
 * `None` until lazy row-count introspection has run.
 */
row_count: number | null; columns: Column[]; primary_key: string[]; foreign_keys: ForeignKey[]; indexes: Index[] }
/**
 * Typed request for browsing one table through the grid. This deliberately
 * does not carry executable SQL; each driver owns safe dialect-specific
 * rendering and value binding.
 */
export type TableBrowseRequest = { connection_id: string; database: string | null; schema: string; table: string; limit: number | null; 
/**
 * Zero-based row offset for page-style table browsing. Drivers should
 * combine this with deterministic ordering when available so table tabs
 * stay stable as users move between pages.
 */
offset: number | null; sorts: TableSortClause[]; filters: TableFilterClause[]; 
/**
 * When no explicit sort is requested, order by the table primary key if
 * metadata is available. This keeps table tabs stable without the UI
 * building an `ORDER BY` string.
 */
primary_key_fallback_ordering: boolean; 
/**
 * When `true`, the driver additionally runs `SELECT count(*)` with the
 * same filter clauses and returns the result in `QueryResult.total_rows`.
 * Defaults to `false` to avoid the extra round-trip on every page flip.
 * Callers should set this on the first page load of a table tab.
 */
include_total?: boolean }
export type TableChangeRequest = { database: string | null; schema: string; table: string; primary_key: string[]; columns: DiffColumn[]; changes: RowChange[] }
export type TableCommitPreview = { sql: string; expected_rows: number; statement_count: number }
export type TableCommitResult = { sql: string; rows_affected: number; duration_ms: number }
export type TableDiff = { name: string; status: ChangeStatus; columns: ColumnDiff[]; indexes: IndexDiff[]; foreign_keys: ForeignKeyDiff[]; primary_key: PrimaryKeyDiff; 
/**
 * Full source/target objects so the UI can render either side verbatim.
 */
source: Table | null; target: Table | null }
export type TableFilterClause = { column: string; operator: TableFilterOperator; 
/**
 * User-entered scalar value. Null checks intentionally use operators
 * instead of overloading this field.
 */
value: string | null }
export type TableFilterOperator = "equals" | "not_equals" | "contains" | "not_contains" | "starts_with" | "ends_with" | 
/**
 * Raw SQL LIKE pattern (`%`/`_` supplied by the user), matched case-insensitively.
 */
"like" | "is_null" | "is_not_null" | "greater_than" | "greater_than_or_equal" | "less_than" | "less_than_or_equal"
export type TableSortClause = { column: string; direction: SortDirection }
/**
 * What kind of database object references a searched table or column. Returned
 * by the `find_usages` command. See SPEC §6.2 (schema navigation).
 */
export type UsageKind = "view" | "materialized_view" | "function" | "procedure" | "trigger" | "constraint"
/**
 * A confirmed reference to the searched table/column found inside a view
 * definition, routine body, trigger definition, or constraint. The reference
 * is structurally confirmed by `cellar-sql` (real identifier, not a substring
 * match) before it ever reaches this type.
 */
export type UsageReference = { kind: UsageKind; 
/**
 * Schema the referencing object lives in.
 */
schema: string; 
/**
 * Name of the referencing object (view / function / trigger / constraint).
 */
name: string; 
/**
 * For triggers and constraints, the table the object is attached to.
 */
on_table: string | null; 
/**
 * 1-based line within `definition` where the reference was found.
 */
line: number; 
/**
 * The matching line, trimmed for display.
 */
snippet: string; 
/**
 * The column matched, when the search was column-scoped.
 */
matched_column: string | null; 
/**
 * Full object definition so the UI can open it in an editor tab.
 */
definition: string }
export type View = { name: string; schema: string; columns: Column[]; definition: string | null }
export type ViewDiff = { name: string; status: ChangeStatus; source: View | null; target: View | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
