import {test,expect} from '@playwright/test';
test('import own database, stage/commit/discard edits, insert/delete rows and download updated SQLite',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/');await expect(page.getByRole('grid')).toBeVisible();
  await page.getByRole('button',{name:'＋ Add connection',exact:true}).click();
  await page.getByRole('button',{name:'SQLite',exact:true}).click();await page.getByRole('tab',{name:'Options',exact:true}).click();
  await page.getByLabel('Import SQLite file').setInputFiles('.fixtures/demo.sqlite');
  await expect(page.getByRole('gridcell').filter({hasText:'Demo customer 001'})).toBeVisible();
  await expect(page.getByText('REVIEWED WRITES')).toBeVisible();
  await page.getByRole('gridcell').filter({hasText:'Demo customer 001'}).dblclick();
  await page.getByLabel('Cell value',{exact:true}).fill('Edited customer');
  await page.getByRole('button',{name:'Stage cell edit'}).click();
  await expect(page.getByText('1 pending',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Review & Commit',exact:true}).click();
  const review=page.getByRole('dialog',{name:'Review and commit'});
  await expect(review.locator('pre')).toContainText('UPDATE "main"."customers"');
  await expect(page.getByRole('button',{name:'Commit transaction'})).toBeDisabled();
  await page.getByLabel('Commit confirmation').fill('COMMIT 1 CHANGES');
  if(process.env.CELLAR_CAPTURE_SCREENSHOTS==='1')await page.screenshot({path:'assets/review-v2.png'});
  await page.getByRole('button',{name:'Commit transaction'}).click();
  await expect(review).not.toBeVisible();
  await expect(page.getByRole('gridcell').filter({hasText:'Edited customer'})).toBeVisible();
  await page.getByRole('gridcell').filter({hasText:'Edited customer'}).dblclick();
  await page.getByLabel('Cell value',{exact:true}).fill('Discard this');await page.getByRole('button',{name:'Stage cell edit'}).click();
  await page.getByRole('button',{name:'Discard changes'}).click();
  await expect(page.getByRole('gridcell').filter({hasText:'Edited customer'})).toBeVisible();
  await page.getByRole('button',{name:'＋ Insert row'}).click();
  await page.getByLabel('Include id',{exact:true}).check();await page.getByLabel('Insert id',{exact:true}).fill('999');
  await page.getByLabel('Include name',{exact:true}).check();await page.getByLabel('Insert name',{exact:true}).fill('Inserted customer');
  await page.getByRole('button',{name:'Stage insert'}).click();await page.getByRole('button',{name:'Review & Commit',exact:true}).click();
  await page.getByLabel('Commit confirmation').fill('COMMIT 1 CHANGES');await page.getByRole('button',{name:'Commit transaction'}).click();
  await expect(page.getByRole('button',{name:'↻ Refresh'})).toBeEnabled();
  await page.getByRole('button',{name:'where',exact:true}).click();await page.getByLabel('Filter column',{exact:true}).selectOption('id');await page.getByLabel('Filter operator').selectOption('equals');await page.getByLabel('Filter value').fill('999');await page.getByRole('button',{name:'＋ Filter',exact:true}).click();
  await expect(page.getByRole('gridcell').filter({hasText:'Inserted customer'})).toBeVisible();
  await page.getByRole('gridcell').filter({hasText:'Inserted customer'}).dblclick();await page.getByRole('button',{name:'Stage row deletion'}).click();
  await page.getByRole('button',{name:'Review & Commit',exact:true}).click();await page.getByLabel('Commit confirmation').fill('COMMIT 1 CHANGES');await page.getByRole('button',{name:'Commit transaction'}).click();
  await expect(page.getByText('No rows matched.')).toBeVisible();
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download database',exact:true}).click();
  expect((await download).suggestedFilename()).toContain('.sqlite');
  await page.getByRole('button',{name:'Clear all',exact:true}).click();
  if(process.env.CELLAR_CAPTURE_SCREENSHOTS==='1')await page.screenshot({path:'assets/workspace-v2.png'});
  await page.getByRole('button',{name:'Edit connection',exact:true}).click();await page.getByRole('tab',{name:'Options',exact:true}).click();await expect(page.getByLabel('Enable editing')).toBeChecked();
  await page.getByLabel('Enable editing').uncheck();await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.getByText('READ ONLY',{exact:true})).toBeVisible();expect(errors).toEqual([]);
});

test('Supabase setup exposes database connection, verified TLS and root certificate fields',async({page})=>{
  await page.goto('/');await expect(page.getByRole('grid')).toBeVisible();await page.getByRole('button',{name:'＋ Add connection',exact:true}).click();
  await page.getByRole('button',{name:'Supabase',exact:true}).click();await expect(page.getByLabel('Database host')).toBeVisible();await expect(page.getByLabel('Database password')).toHaveAttribute('type','password');
  await expect(page.getByText('Use the PostgreSQL direct or session-pooler')).toBeVisible();await page.getByRole('tab',{name:'SSL / TLS',exact:true}).click();await expect(page.getByLabel('Root certificate')).toBeVisible();
  if(process.env.CELLAR_CAPTURE_SCREENSHOTS==='1')await page.screenshot({path:'assets/connections-v2.png'});
});
