import {test,expect} from '@playwright/test';

test('content-fit columns retain keyboard navigation across horizontal scroll',async({page})=>{
  await page.goto('/');await expect(page.getByRole('grid')).toBeVisible();
  await expect(page.locator('.head-number')).toHaveCSS('width','36px');
  await expect(page.locator('.grid-head')).toHaveCSS('height','26px');
  await expect(page.getByRole('button',{name:'customers',exact:true})).toBeVisible();
  await expect(page.locator('.native-filter>button').first()).toHaveAttribute('aria-label','↻ Refresh');
  await expect(page.getByLabel('Quick filter column')).toHaveValue('name');
  await page.getByLabel('Quick filter column').selectOption('email');
  await page.getByLabel('Quick filter',{exact:true}).fill('customer1@example.test');
  await page.getByLabel('Quick filter',{exact:true}).press('Enter');
  await expect(page.getByRole('grid')).toHaveAttribute('aria-rowcount','2');
  await expect(page.getByRole('gridcell',{name:'Demo customer 001',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Clear all',exact:true}).click();
  await page.getByRole('button',{name:/▦ orders/}).click();
  const heads=page.getByRole('columnheader');
  await expect(heads).toHaveCount(6);
  const widths=await heads.evaluateAll(elements=>elements.map(element=>element.getBoundingClientRect().width));
  expect(new Set(widths).size).toBeGreaterThan(1);
  await page.setViewportSize({width:900,height:700});
  await page.getByRole('gridcell',{name:'1',exact:true}).first().click();
  for(let index=0;index<5;index++)await page.keyboard.press('ArrowRight');
  const selected=page.locator('[role=gridcell][aria-selected=true]');
  await expect(selected).toHaveAttribute('aria-colindex','6');
  await expect(selected).toContainText('synthetic');
  expect(await page.getByRole('grid').evaluate(element=>element.scrollLeft)).toBeGreaterThan(0);
  for(let index=0;index<5;index++)await page.keyboard.press('ArrowLeft');
  await expect(page.locator('[role=gridcell][aria-selected=true]')).toHaveAttribute('aria-colindex','1');
  await page.setViewportSize({width:1440,height:1300});
  await expect(page.getByRole('gridcell',{name:'30',exact:true}).first()).toBeVisible();
  const separator=await page.getByRole('separator',{name:'Resize sidebar',exact:true}).boundingBox();
  await page.mouse.move(separator!.x+2,separator!.y+20);await page.mouse.down();
  await page.mouse.move(separator!.x+130,separator!.y+20);await page.mouse.up();
  await expect(page.locator('.native-sidebar')).toHaveCSS('width','384px');
  await page.reload();await expect(page.locator('.native-sidebar')).toHaveCSS('width','384px');
  await page.keyboard.press('Meta+k');
  const search=page.getByRole('dialog',{name:'Search workspace',exact:true});
  await search.getByLabel('Search tables, columns, queries',{exact:true}).fill('metadata');
  await expect(search.getByRole('button',{name:/main.orders/})).toBeVisible();
  await expect(search.getByRole('button',{name:/main.orders/})).toBeEnabled();
  await search.getByLabel('Search tables, columns, queries',{exact:true}).press('Enter');
  await expect(search).toHaveCount(0);await expect(page.getByRole('button',{name:'orders',exact:true})).toBeVisible();
  await expect(page.getByRole('grid')).toBeVisible();
  await page.setViewportSize({width:1512,height:891});
  await page.getByRole('tab',{name:/^Messages/}).click();
  await page.screenshot({path:'assets/cellar-ui-review-dark.png'});
  await page.getByRole('button',{name:'Theme',exact:true}).click();
  await page.screenshot({path:'assets/cellar-ui-review-light.png'});
});
