import { test, expect } from '@playwright/test';
test('SQLite workspace browsing, filters, paging, SQL errors and screenshots', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('grid')).toBeVisible();
  await page.getByRole('button', { name: /▦ orders/ }).click();
  await expect(page.getByRole('gridcell').filter({ hasText: 'synthetic' }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await expect(page.getByText('Page 2 · 100 rows')).toBeVisible();
  await page.getByRole('button',{name:'where',exact:true}).click();
  await page.getByLabel('Filter column',{exact:true}).selectOption('status');
  await page.getByLabel('Filter operator').selectOption('equals');
  await page.getByLabel('Filter value').fill('paid');
  await page.getByRole('button', { name: '＋ Filter', exact: true }).click();
  await expect(page.getByRole('button', { name: 'status equals paid ×' })).toBeVisible();
  await expect(page.getByRole('gridcell').filter({ hasText: /^paid$/ }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Structure', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'metadata', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: /^Results/ }).click();
  if (process.env.CELLAR_CAPTURE_SCREENSHOTS === '1') await page.screenshot({ path: 'assets/workspace-sqlite.png' });
  await page.getByRole('button', { name: '＋ New SQL query' }).click();
  const editor = page.locator('.cm-content');
  await editor.click();
  await page.keyboard.press('Meta+a');
  await page.keyboard.insertText('SELECT status, count(*) AS count FROM orders GROUP BY status ORDER BY status');
  await page.getByRole('button', { name: '▶ Run query' }).click();
  await expect(page.getByRole('gridcell').filter({ hasText: /^paid$/ })).toBeVisible();
  if (process.env.CELLAR_CAPTURE_SCREENSHOTS === '1') await page.screenshot({ path: 'assets/workspace-sql.png' });
  await editor.click();
  await page.keyboard.press('Meta+a');
  await page.keyboard.insertText('DELETE FROM orders');
  await page.getByRole('button', { name: '▶ Run query' }).click();
  await expect(page.getByRole('alert')).toContainText('read-only SELECT');
  expect(errors).toEqual([]);
});
test('loopback preview rejects unauthenticated requests', async ({ request }) => {
  const response = await request.post('/api/tool', { data: { name: 'cellar_open', args: {} } });
  expect(response.status()).toBe(403);
});
test('SQL batches, plans and foreign-key navigation work in the UI', async ({page})=>{
  await page.goto('/');await expect(page.getByRole('grid')).toBeVisible();
  await page.getByRole('button',{name:/▦ orders/}).click();
  await page.getByRole('button',{name:'Structure',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Indexes',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'main.customers.id',exact:true}).click();
  await expect(page.getByRole('gridcell').filter({hasText:'Demo customer 001'})).toBeVisible();
  await page.getByRole('button',{name:'＋ New SQL query'}).click();
  await page.locator('.cm-content').click();await page.keyboard.press('Meta+a');
  await page.keyboard.insertText('SELECT 11 AS first; SELECT 22 AS second;');
  await page.getByRole('button',{name:'Run all (max 10)',exact:true}).click();
  await expect(page.getByRole('button',{name:/Statement 1 · 1 rows/})).toBeVisible();
  await expect(page.getByRole('gridcell',{name:'22',exact:true})).toBeVisible();
  await page.getByRole('button',{name:/Statement 1 · 1 rows/}).click();
  await expect(page.getByRole('gridcell',{name:'11',exact:true})).toBeVisible();
  await page.locator('.cm-content').click();await page.keyboard.press('Meta+a');
  await page.keyboard.insertText('SELECT * FROM orders WHERE id = 1');
  await page.getByRole('button',{name:'Explain',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Query plan'}).locator('pre')).toContainText('SEARCH');
});
test('Postgres workspace runs against the disposable fixture', async ({ page }) => {
  test.skip(process.env.CELLAR_TEST_POSTGRES !== '1');
  await page.goto('/');
  await expect(page.getByRole('grid')).toBeVisible();
  await page.getByLabel('Connection', { exact: true }).selectOption('demo-postgres');
  await expect(page.getByRole('grid')).toBeVisible();
  await page.getByRole('button', { name: /▦ orders/ }).click();
  await expect(page.getByRole('gridcell').filter({ hasText: 'synthetic' }).first()).toBeVisible();
  if (process.env.CELLAR_CAPTURE_SCREENSHOTS === '1') await page.screenshot({ path: 'assets/workspace-postgres.png' });
});
