import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp,copyFile,readFile,rm,realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { dispatch } from '../server/tools.js';
import type { Change,Result,Connection } from '../ui/types.js';
import {fileURLToPath} from 'node:url';
process.env.CELLAR_EXTENSION_CONFIG??=fileURLToPath(new URL('../.fixtures/connections.json',import.meta.url));

test('custom SQLite profiles, reviewed edits, rollback, conflicts and snapshot download',async()=>{
  const directory=await mkdtemp(join(tmpdir(),'cellar-edits-'));
  const previous=process.env.CELLAR_EXTENSION_STATE;
  process.env.CELLAR_EXTENSION_STATE=directory;
  try {
    const database=join(directory,'custom.sqlite');await copyFile(new URL('../.fixtures/demo.sqlite',import.meta.url),database);
    const saved=await dispatch('cellar_connection',{operation:'save',profile:{name:'Custom SQLite',engine:'sqlite',database,allow_edits:true,env_tag:'local'}});
    const connection=(saved.connections as Connection[]).at(-1)!;
    assert.equal(connection.readOnly,false);
    const detail=await dispatch('cellar_connection',{operation:'details',connection:connection.id});
    assert.equal((detail.profile as {database:string}).database,await realpath(database));
    const args={connection:connection.id,schema:'main',table:'orders'};
    const read=async()=>await dispatch('cellar_browse',args) as unknown as Result;
    const base=await read();
    const update:Change={kind:'update',original:base.rows[0],revision:base.revisions![0],values:{status:"Edited O'Brien"}};
    const changes=[update,{kind:'insert',values:{id:'999',status:'New synthetic row'}},{kind:'delete',original:base.rows[1],revision:base.revisions![1],values:{}}];
    const preview=await dispatch('cellar_preview',{...args,changes});
    assert.ok(String(preview.sql).includes("Edited O''Brien"));
    assert.equal((await read()).rows[0][2],base.rows[0][2]);
    await assert.rejects(dispatch('cellar_commit',{...args,changes,preview_id:preview.previewId,confirmation:'COMMIT 1 CHANGES'}),/confirm/);
    const result=await dispatch('cellar_commit',{...args,changes,preview_id:preview.previewId,confirmation:'COMMIT 3 CHANGES'});
    assert.equal(result.committed,true);
    assert.equal((await read()).rows[0][2],"Edited O'Brien");
    await assert.rejects(dispatch('cellar_commit',{...args,changes,preview_id:preview.previewId,confirmation:'COMMIT 3 CHANGES'}),/changed/);
    const fresh=await read();
    const rollback=[{kind:'update',original:fresh.rows[0],revision:fresh.revisions![0],values:{status:'Must roll back'}},{kind:'insert',values:{id:'999',status:'Duplicate key'}}];
    const failed=await dispatch('cellar_preview',{...args,changes:rollback});
    await assert.rejects(dispatch('cellar_commit',{...args,changes:rollback,preview_id:failed.previewId,confirmation:'COMMIT 2 CHANGES'}),/constraints/);
    assert.equal((await read()).rows[0][2],"Edited O'Brien");
    const download=await dispatch('cellar_export',{connection:connection.id,stage:'prepare'});
    const chunk=await dispatch('cellar_export',{connection:connection.id,stage:'chunk',id:download.id,offset:0});
    assert.ok(Buffer.from(chunk.chunk as string,'base64').subarray(0,16).equals(Buffer.from('SQLite format 3\0')));
    await dispatch('cellar_export',{connection:connection.id,stage:'finish',id:download.id});
    const source=await readFile(database);
    const uploaded=await dispatch('cellar_upload',{stage:'begin',name:'Chat attachment.sqlite'});
    for(let offset=0;offset<source.length;offset+=32768)await dispatch('cellar_upload',{stage:'chunk',id:uploaded.id,chunk:source.subarray(offset,offset+32768).toString('base64')});
    const imported=await dispatch('cellar_upload',{stage:'finish',id:uploaded.id});
    assert.equal(imported.importedCopy,true);
    assert.equal((imported.connections as Connection[]).at(-1)!.name,'Chat attachment.sqlite');
    const stored=JSON.parse(await readFile(join(directory,'profiles.json'),'utf8'));
    assert.equal(stored.length,2);
    assert.ok(!JSON.stringify(stored).includes('password":"'));
    await dispatch('cellar_connection',{operation:'save',profile:{id:connection.id,name:'Renamed connection',engine:'sqlite',database,allow_edits:false}});
    assert.equal(JSON.parse(await readFile(join(directory,'profiles.json'),'utf8')).length,2);
    await dispatch('cellar_connection',{operation:'remove',connection:connection.id});
    assert.equal(JSON.parse(await readFile(join(directory,'profiles.json'),'utf8')).length,1);
    await assert.rejects(dispatch('cellar_commit',{connection:'demo-sqlite',schema:'main',table:'customers',changes:[update],preview_id:preview.previewId,confirmation:'COMMIT 1 CHANGES'}),/Enable editing/);
    await assert.rejects(dispatch('cellar_connection',{operation:'save',profile:{name:'Invalid',engine:'sqlite',database:join(directory,'profiles.json')}}),/not SQLite/);
  } finally {if(previous)process.env.CELLAR_EXTENSION_STATE=previous;else delete process.env.CELLAR_EXTENSION_STATE;await rm(directory,{recursive:true,force:true});}
});
