import {useState} from 'react';
import {Icon} from './Shell.js';
import {exportResult} from './export.js';
import type {Tab} from './types.js';

export function GridFooter({tab,busy,editable,onInsert,onDiscard,onReview,onPage}:{tab:Tab;busy:boolean;editable:boolean;onInsert:()=>void;onDiscard:()=>void;onReview:()=>void;onPage:(offset:number)=>void}) {
  const [exporting,setExporting]=useState(false);
  const pending=tab.changes?.length??0;
  return <div className="grid-footer">
    <div className="export-menu"><button aria-label="Export table page" title="Export table page" disabled={!tab.result} onClick={()=>setExporting(!exporting)}><Icon name="download"/><Icon name="chevron-down"/></button>{exporting&&tab.result&&<div className="native-menu"><button onClick={()=>{exportResult(tab.result!,'csv',tab.title);setExporting(false);}} aria-label="Export CSV page">CSV</button><button onClick={()=>{exportResult(tab.result!,'tsv',tab.title);setExporting(false);}} aria-label="Export TSV page">TSV</button><button onClick={()=>{exportResult(tab.result!,'json',tab.title);setExporting(false);}} aria-label="Export JSON page">JSON</button><button disabled title="SQL export is not available in this extension">SQL</button><small className="export-scope">Current loaded page only</small></div>}</div>
    {editable&&<><button disabled title="Import CSV is unavailable in this extension" aria-label="Import CSV"><Icon name="upload"/></button><span className="footer-divider"/><span className={pending?'pending-count changed':'pending-count'}>{pending} pending</span><button aria-label="＋ Insert row" title="Insert row" disabled={busy||pending>=50} onClick={onInsert}><Icon name="plus"/></button><button disabled title="Set NULL in the cell editor" aria-label="Set selected cell NULL"><Icon name="null"/></button><button disabled title="Edit boolean in the cell editor" aria-label="Toggle selected boolean"><Icon name="type-bool"/></button><button disabled title="Delete a row from the cell editor" aria-label="Delete selected row"><Icon name="trash"/></button><button aria-label="Discard changes" title="Discard changes" disabled={busy||!pending} onClick={onDiscard}><Icon name="undo"/></button><button aria-label="Review & Commit" title="Review & Commit" disabled={busy||!pending} onClick={onReview}><Icon name="commit"/></button></>}
    <span className="footer-spacer"/><span className="page-summary">{tab.result?.rows.length??0} rows · {tab.result?.durationMs??0} ms {tab.result?.truncated?'· response capped / more rows may exist':''}</span><span className="page-summary">Page {Math.floor(tab.offset/100)+1} · 100 rows</span><button aria-label="Previous" title="Previous page" disabled={busy||tab.offset===0} onClick={()=>onPage(Math.max(0,tab.offset-100))}><Icon name="chevron-left"/></button><button aria-label="Next" title="Next page" disabled={busy||!tab.result?.truncated||tab.result.rows.length!==100} onClick={()=>onPage(tab.offset+100)}><Icon name="chevron-right"/></button>
  </div>;
}
